### ISSUE TITLE
To-do:

### ISSUE THREAD

**Issue by ARampey** [ARampey/hls-sim#1]
Camera
* [ ] follow capsule
* [ ] zoom in/out

UI
* [ ] display for trajectory, speed, etc

Capsule
* [ ] trajectory

Physics-y stuff
* [ ] earth rotation
* [ ] moon rotation
* [ ] earth orbit
* [ ] moon orbit
* [ ] earth gravity
* [ ] moon gravity

Terrain
* [ ] texture map s.pole moon
* [ ] finish earth shader
